var shinkanzenData = [
{kanji:"相変わらず",kana:"あいかわらず",meaning:"vẫn như mọi khi"},
{kanji:"相次いで",kana:"あいついで",meaning:"liên tiếp"},
{kanji:"アイデア",kana:"あいであ",meaning:"ý tưởng"},
{kanji:"あいまい",kana:"あいまい",meaning:"mơ hồ"},
{kanji:"遭う",kana:"あう",meaning:"gặp phải"},
{kanji:"青白い",kana:"あおじろい",meaning:"xanh xao"},
{kanji:"赤字",kana:"あかじ",meaning:"lỗ,thâm hụt"},
{kanji:"飽きる",kana:"あきる",meaning:"chán"},
{kanji:"あきらめる",kana:"あきらめる",meaning:"từ bỏ"},
{kanji:"握手",kana:"あくしゅ",meaning:"bắt tay"},
{kanji:"あくび",kana:"あくび",meaning:"ngáp"},
{kanji:"明け方",kana:"あけがた",meaning:"rạng đông"},
{kanji:"揚げる",kana:"あげる",meaning:"chiên"},
{kanji:"あこがれる",kana:"あこがれる",meaning:"ngưỡng mộ"},
{kanji:"味わう",kana:"あじわう",meaning:"nếm, thưởng thức"},
{kanji:"預ける",kana:"あずける",meaning:"gửi"},
{kanji:"汗",kana:"あせ",meaning:"mồ hôi"},
{kanji:"与える",kana:"あたえる",meaning:"trao"},
{kanji:"温める",kana:"あたためる",meaning:"làm ấm"},
{kanji:"頭に来る",kana:"あたまにくる",meaning:"điên tiết"},
{kanji:"扱い",kana:"あつかい",meaning:"cách đối xử"},
{kanji:"集まり",kana:"あつまり",meaning:"buổi tụ tập"},
{kanji:"厚み",kana:"あつみ",meaning:"độ dày"},
{kanji:"暴れる",kana:"あばれる",meaning:"quậy phá"},
{kanji:"甘み",kana:"あまみ",meaning:"độ ngọt"},
{kanji:"危うい",kana:"あやうい",meaning:"nguy hiểm"},
{kanji:"荒い",kana:"あらい",meaning:"thô"},
{kanji:"あらかじめ",kana:"あらかじめ",meaning:"trước"},
{kanji:"あらすじ",kana:"あらすじ",meaning:"tóm tắt"},
{kanji:"改める",kana:"あらためる",meaning:"sửa đổi"},
{kanji:"ありがたい",kana:"ありがたい",meaning:"biết ơn"},
{kanji:"哀れ",kana:"あわれ",meaning:"đáng thương"},
{kanji:"案外",kana:"あんがい",meaning:"không ngờ"},
{kanji:"暗記",kana:"あんき",meaning:"học thuộc"},
{kanji:"意外",kana:"いがい",meaning:"ngoài dự đoán"},
{kanji:"生き生き",kana:"いきいき",meaning:"sống động"},
{kanji:"いきなり",kana:"いきなり",meaning:"đột nhiên"},
{kanji:"意義深い",kana:"いぎぶかい",meaning:"ý nghĩa sâu sắc"},
{kanji:"依然",kana:"いぜん",meaning:"vẫn"},
{kanji:"抱く",kana:"いだく",meaning:"ôm"},
{kanji:"位置",kana:"いち",meaning:"vị trí"},
{kanji:"一応",kana:"いちおう",meaning:"tạm thời"},
{kanji:"一瞬",kana:"いっしゅん",meaning:"trong chốc lát"},
{kanji:"一致",kana:"いっち",meaning:"nhất trí"},
{kanji:"移転",kana:"いてん",meaning:"chuyển"},
{kanji:"違反",kana:"いはん",meaning:"vi phạm"},
{kanji:"いよいよ",kana:"いよいよ",meaning:"cuối cùng"},
{kanji:"依頼",kana:"いらい",meaning:"nhờ vả"},
{kanji:"引用",kana:"いんよう",meaning:"trích dẫn"},
{kanji:"受け入れる",kana:"うけいれる",meaning:"tiếp nhận"},
{kanji:"失う",kana:"うしなう",meaning:"mất"},
{kanji:"疑う",kana:"うたがう",meaning:"nghi ngờ"},
{kanji:"訴える",kana:"うったえる",meaning:"tố cáo"},
{kanji:"奪う",kana:"うばう",meaning:"cướp"},
{kanji:"恨む",kana:"うらむ",meaning:"oán hận"},
{kanji:"永遠",kana:"えいえん",meaning:"vĩnh viễn"},
{kanji:"影響",kana:"えいきょう",meaning:"ảnh hưởng"},
{kanji:"栄養",kana:"えいよう",meaning:"dinh dưỡng"},
{kanji:"演技",kana:"えんぎ",meaning:"diễn xuất"},
{kanji:"援助",kana:"えんじょ",meaning:"viện trợ"},
{kanji:"応援",kana:"おうえん",meaning:"ủng hộ"},
{kanji:"横断",kana:"おうだん",meaning:"băng qua"},
{kanji:"大幅",kana:"おおはば",meaning:"diện rộng"},
{kanji:"犯す",kana:"おかす",meaning:"phạm (tội)"},
{kanji:"補う",kana:"おぎなう",meaning:"bổ sung"},
{kanji:"抑える",kana:"おさえる",meaning:"kìm nén"},
{kanji:"惜しむ",kana:"おしむ",meaning:"tiếc nuối"},
{kanji:"恐らく",kana:"おそらく",meaning:"có lẽ"},
{kanji:"落ち込む",kana:"おちこむ",meaning:"chán nản"},
{kanji:"思い切る",kana:"おもいきる",meaning:"quyết tâm"},
{kanji:"思い込む",kana:"おもいこむ",meaning:"tin rằng"},
{kanji:"思い出す",kana:"おもいだす",meaning:"nhớ lại"},
{kanji:"面白み",kana:"おもしろみ",meaning:"sự thú vị"},
{kanji:"恩",kana:"おん",meaning:"ân huệ"},
{kanji:"温暖化",kana:"おんだんか",meaning:"nóng lên toàn cầu"},
{kanji:"開発",kana:"かいはつ",meaning:"phát triển"},
{kanji:"解決",kana:"かいけつ",meaning:"giải quyết"},
{kanji:"回復",kana:"かいふく",meaning:"hồi phục"},
{kanji:"改正",kana:"かいせい",meaning:"sửa đổi"},
{kanji:"改善",kana:"かいぜん",meaning:"cải thiện"},
{kanji:"確認",kana:"かくにん",meaning:"xác nhận"},
{kanji:"革命",kana:"かくめい",meaning:"cách mạng"},
{kanji:"拡大",kana:"かくだい",meaning:"mở rộng"},
{kanji:"確保",kana:"かくほ",meaning:"đảm bảo"},
{kanji:"過去",kana:"かこ",meaning:"quá khứ"},
{kanji:"課題",kana:"かだい",meaning:"vấn đề"},
{kanji:"片道",kana:"かたみち",meaning:"một chiều"},
{kanji:"活躍",kana:"かつやく",meaning:"hoạt động tích cực"},
{kanji:"悲しむ",kana:"かなしむ",meaning:"đau buồn"},
{kanji:"必ずしも",kana:"かならずしも",meaning:"không hẳn"},
{kanji:"感染",kana:"かんせん",meaning:"lây nhiễm"},
{kanji:"管理",kana:"かんり",meaning:"quản lý"},
{kanji:"危機",kana:"きき",meaning:"khủng hoảng"},
{kanji:"期待",kana:"きたい",meaning:"kỳ vọng"},
{kanji:"希望",kana:"きぼう",meaning:"hy vọng"},
{kanji:"記録",kana:"きろく",meaning:"ghi chép"},
{kanji:"緊張",kana:"きんちょう",meaning:"căng thẳng"},
{kanji:"偶然",kana:"ぐうぜん",meaning:"ngẫu nhiên"},
{kanji:"具体的",kana:"ぐたいてき",meaning:"cụ thể"},
{kanji:"悔やむ",kana:"くやむ",meaning:"hối tiếc"},
{kanji:"経営",kana:"けいえい",meaning:"kinh doanh"},
{kanji:"経済",kana:"けいざい",meaning:"kinh tế"},
{kanji:"結果",kana:"けっか",meaning:"kết quả"},
{kanji:"決して",kana:"けっして",meaning:"quyết không"},
{kanji:"現状",kana:"げんじょう",meaning:"hiện trạng"},
{kanji:"権力",kana:"けんりょく",meaning:"quyền lực"},
{kanji:"効率",kana:"こうりつ",meaning:"hiệu quả"},
{kanji:"広告",kana:"こうこく",meaning:"quảng cáo"},
{kanji:"交渉",kana:"こうしょう",meaning:"đàm phán"},
{kanji:"向上",kana:"こうじょう",meaning:"nâng cao"},
{kanji:"構成",kana:"こうせい",meaning:"cấu thành"},
{kanji:"国際",kana:"こくさい",meaning:"quốc tế"},
{kanji:"誤解",kana:"ごかい",meaning:"hiểu lầm"},
{kanji:"混乱",kana:"こんらん",meaning:"hỗn loạn"},
{kanji:"再開",kana:"さいかい",meaning:"mở lại"},
{kanji:"災害",kana:"さいがい",meaning:"thiên tai"},
{kanji:"最高",kana:"さいこう",meaning:"cao nhất"},
{kanji:"最大",kana:"さいだい",meaning:"lớn nhất"},
{kanji:"削減",kana:"さくげん",meaning:"cắt giảm"},
{kanji:"作成",kana:"さくせい",meaning:"soạn thảo"},
{kanji:"避ける",kana:"さける",meaning:"tránh"},
{kanji:"撮影",kana:"さつえい",meaning:"quay phim"},
{kanji:"支援",kana:"しえん",meaning:"hỗ trợ"},
{kanji:"支払う",kana:"しはらう",meaning:"thanh toán"},
{kanji:"失敗",kana:"しっぱい",meaning:"thất bại"},
{kanji:"失望",kana:"しつぼう",meaning:"thất vọng"},
{kanji:"実施",kana:"じっし",meaning:"thực hiện"},
{kanji:"実現",kana:"じつげん",meaning:"thực hiện được"},
{kanji:"自然",kana:"しぜん",meaning:"tự nhiên"},
{kanji:"指導",kana:"しどう",meaning:"chỉ đạo"},
{kanji:"次第に",kana:"しだいに",meaning:"dần dần"},
{kanji:"従う",kana:"したがう",meaning:"theo"},
{kanji:"主張",kana:"しゅちょう",meaning:"chủ trương"},
{kanji:"集中",kana:"しゅうちゅう",meaning:"tập trung"},
{kanji:"収入",kana:"しゅうにゅう",meaning:"thu nhập"},
{kanji:"修正",kana:"しゅうせい",meaning:"sửa chữa"},
{kanji:"需要",kana:"じゅよう",meaning:"nhu cầu"},
{kanji:"状況",kana:"じょうきょう",meaning:"tình hình"},
{kanji:"情報",kana:"じょうほう",meaning:"thông tin"},
{kanji:"証明",kana:"しょうめい",meaning:"chứng minh"},
{kanji:"責任",kana:"せきにん",meaning:"trách nhiệm"},
{kanji:"選択",kana:"せんたく",meaning:"lựa chọn"},
{kanji:"存在",kana:"そんざい",meaning:"tồn tại"},
{kanji:"対応",kana:"たいおう",meaning:"đối ứng"},
{kanji:"対象",kana:"たいしょう",meaning:"đối tượng"},
{kanji:"態度",kana:"たいど",meaning:"thái độ"},
{kanji:"達成",kana:"たっせい",meaning:"đạt được"},
{kanji:"担当",kana:"たんとう",meaning:"phụ trách"},
{kanji:"調査",kana:"ちょうさ",meaning:"điều tra"},
{kanji:"直接",kana:"ちょくせつ",meaning:"trực tiếp"},
{kanji:"提案",kana:"ていあん",meaning:"đề xuất"},
{kanji:"適切",kana:"てきせつ",meaning:"thích hợp"},
{kanji:"努力",kana:"どりょく",meaning:"nỗ lực"},
{kanji:"内容",kana:"ないよう",meaning:"nội dung"},
{kanji:"認識",kana:"にんしき",meaning:"nhận thức"},
{kanji:"能力",kana:"のうりょく",meaning:"năng lực"},
{kanji:"判断",kana:"はんだん",meaning:"phán đoán"},
{kanji:"批判",kana:"ひはん",meaning:"phê phán"},
{kanji:"評価",kana:"ひょうか",meaning:"đánh giá"},
{kanji:"表現",kana:"ひょうげん",meaning:"biểu hiện"},
{kanji:"不安",kana:"ふあん",meaning:"bất an"},
{kanji:"武器",kana:"ぶき",meaning:"vũ khí"},
{kanji:"変更",kana:"へんこう",meaning:"thay đổi"},
{kanji:"防止",kana:"ぼうし",meaning:"phòng chống"},
{kanji:"目的",kana:"もくてき",meaning:"mục đích"},
{kanji:"問題",kana:"もんだい",meaning:"vấn đề"},
{kanji:"要求",kana:"ようきゅう",meaning:"yêu cầu"},
{kanji:"理由",kana:"りゆう",meaning:"lý do"},
{kanji:"理解",kana:"りかい",meaning:"hiểu"},
{kanji:"連絡",kana:"れんらく",meaning:"liên lạc"}
]